spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url:
    username:
    password:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
  security:
    user:
      name: account
  jwt:
    secret:
server:
  port: 3000
  shutdown: graceful
  servlet:
    context-path: /api/v1
springdoc:
  swagger-ui:
    path: /swagger
    groups-order: desc
  api-docs:
    path: /api-docs
  show-actuator: true
cloud:
  aws:
    s3:
      bucket:
    credentials:
      access-key:
      secret-key:
    region:
      static:
      auto: false
    stack:
      auto: false
omni:
  X-Api-Key:
  url:
  get-key:
  get-url:
  recommend-url:
  recommend-key: