spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/closeathand?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
server:
  port: 3000
  shutdown: graceful
  servlet:
    context-path: /api/v1
springdoc:
  swagger-ui:
    path: /swagger
    groups-order: desc
  api-docs:
    path: /api-docs
  show-actuator: true
cloud:
  aws:
    s3:
      bucket: rainmirror
    credentials:
      access-key: AKIAV4KMUIH6OSIDLCOV
      secret-key: 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
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false